// <auto-generated />
using System;
using MPTWA_Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MPTWA_Infrastructure.Migrations
{
    [DbContext(typeof(LogContext))]
    partial class LogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MPTWA_Domain.Entities.RequestLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("KeyWord")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_word");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section");

                    b.HasKey("Id")
                        .HasName("pk_request_logs");

                    b.ToTable("request_logs", (string)null);
                });

            modelBuilder.Entity("MPTWA_Domain.Entities.ResultsLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_time")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("RequestLogEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_log_entity_id");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_text");

                    b.Property<int>("VowelsCount")
                        .HasColumnType("integer")
                        .HasColumnName("vowels_count");

                    b.HasKey("Id")
                        .HasName("pk_results_logs");

                    b.HasIndex("RequestLogEntityId")
                        .HasDatabaseName("ix_results_logs_request_log_entity_id");

                    b.ToTable("results_logs", (string)null);
                });

            modelBuilder.Entity("MPTWA_Domain.Entities.ResultsLog", b =>
                {
                    b.HasOne("MPTWA_Domain.Entities.RequestLogEntity", "RequestLogEntity")
                        .WithMany("Results")
                        .HasForeignKey("RequestLogEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_results_logs_request_logs_request_log_entity_id");

                    b.Navigation("RequestLogEntity");
                });

            modelBuilder.Entity("MPTWA_Domain.Entities.RequestLogEntity", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
